"""Change hyd_status field type to Integer

Revision ID: 13da65ac2a05
Revises: 6955eb3692ab
Create Date: 2024-11-17 01:20:17.085119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13da65ac2a05'
down_revision = '6955eb3692ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rawdata', schema=None) as batch_op:
        batch_op.alter_column('hyd_status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rawdata', schema=None) as batch_op:
        batch_op.alter_column('hyd_status',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
