"""Add hyd_status column to rawdata table

Revision ID: 998c1bfed664
Revises: 
Create Date: 2024-11-17 00:46:54.927477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998c1bfed664'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rawdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hyd_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rawdata', schema=None) as batch_op:
        batch_op.drop_column('hyd_status')

    # ### end Alembic commands ###
